### ISSUE TITLE
Receiving 404 error

### ISSUE THREAD

**Issue by Oroton** [BlackScorp/webrpg#3]
Sessions, 
Database all working. 
but I receive a 404 error when pressing creating dummy user

**Comment by BlackScorp** [comment]
in your Server the directory index is disabled http://httpd.apache.org/docs/2.0/mod/mod_dir.html#directoryindex  i tried to fix it with the .htaccess file. update the source code. maybe it will work now.

**Comment by BlackScorp** [comment]
https://github.com/BlackScorp/webrpg/blob/master/public/.htaccess  this should fix it

**Comment by Oroton** [comment]
no 404 error. 
Uploaded  .htaccess. 

But nothing happens now when I click on create dummy.
it goes to
http://webrpg.brissyriders.com/dummyUser

But still showing the login page

**Comment by BlackScorp** [comment]
i updated the public/index.php it should work now;)

**Comment by Oroton** [comment]
still no change

is it ok to post urls on Git?

**Comment by BlackScorp** [comment]
yeah no problem, can you add var_dump($_SERVER) to public/index.php ? have to check what is going on there

**Comment by Oroton** [comment]
added

echo var_dump($_SERVER);

http://webrpg.brissyriders.com/

**Comment by BlackScorp** [comment]
and var_dump($request)

**Comment by Oroton** [comment]
done

**Comment by BlackScorp** [comment]
@Oroton your public/index.php should look like this http://pastebin.com/HFKWsUSW

**Comment by BlackScorp** [comment]
@Oroton the Problem is defined here http://php.net/manual/de/function.filter-input.php#77307  really tricky one, i fixed it in public/index.php

**Comment by Oroton** [comment]
updated.
it just shows.

string(0) ""
